development:
  adapter: postgresql
  encoding: unicode
  database: myyelp_development
  pool: 5
  username: ubuntu
  password: password 

test:
  adapter: postgresql
  encoding: unicode
  database: myyelp_test
  pool: 5
  username: ubuntu
  password: