# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe07804b46e57a17cfb98dba8ea66a60fd8f08e55df84b7129def68576ea4295e36b7b4f1ebf50ce3286f1a9d0517b15ac3acec45947847ccb91aa68bb1950f9

test:
  secret_key_base: 5f23c59bcb2f7b685c1c9192a576a9cba4dd17aeb6a118a5e5a425d54a17cfca8a240aed8e6a1fc5e783a8091f02457bbc0f735f61910eaa574517dd592e4790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
